apiVersion: 1

deleteDatasources:
  - name: graphite-web
    orgId: 1

datasources:
- name: carbon-clickhouse
  type: graphite
  access: proxy
  orgId: 1
  url: http://graphite/
  password:
  user:
  database:
  basicAuth:
  basicAuthUser:
  basicAuthPassword:
  withCredentials:
  isDefault: true
  jsonData:
     graphiteVersion: "1.1"
     tlsAuth:
     tlsAuthWithCACert:
  secureJsonData:
    tlsCACert: "..."
    tlsClientCert: "..."
    tlsClientKey: "..."
  version: 1
  editable: true
